String.prototype.arr=function(index,replace,divider='!') {let a=this.split(divider);if(replace==u){return(a[index])}else{a[index]=replace;return(a.join(divider))}}//Treat a string as an array with dividers. ex: '123!456' is ['123','456']
Array.prototype.cyc=function(index){if(index<0){return(this.toReversed()[Math.abs(index)%this.length])};return(this[index%this.length])}//Get the overflow index value. ex: [1,2,3].cyc(1)==2 and [1,2,3].cyc(4)==2
Array.prototype.list=function(item,array,deep){let a=[];if(deep==u){this.forEach((b,c)=>{if(b==item){a.push(c)}})}else{this.forEach((b,c)=>{if(b.includes(item)){a.push(c)}})};if(array==u){return(a)}else{return(a.map(b=>array[b]))}}//returns an array of indexes that equal item | returns an array from indexes of array where item matches the origin array | deep mode searches strings
//html functions
function btn($a,$b) {return('<button onclick="'+$b+'"><big>'+$a+'</big></button>')}
function col($a,$b) {return("<font color="+$a+">"+$b+"</font>")}
function fun($a,$b) {elm($a).innerHTML=eval('`'+$b+'`')}
function lst($a,$b,$c) {let $0='';let $2=$b.split(',');let $3=($c)=>{let $4=$2[$c].split(':');$1+=('<option value="'+$4[1]+'">'+$4[0]+'</option>')};if($c!=u){$0=' onchange="'+$c+'"'};let $1='<select id="'+$a+'"'+$0+'>';Object.keys($2).forEach($3);$1+='</select>';return($1)}
//data functions (updates saved variables)
function quest($a,$b,$c) {if($a=='add'){add('quests',[$b,loc(),$c])}else{let $1=qname.list($b);let $2=qloc.list(loc());let $3=$1.length-1;let $4=$2.length-1;while($3>-1&&$4>-1){if($1[$3]==$2[$4]){$3=$1[$3];break}else if($1[$3]>$2[$4]){$3-=1}else{$4-=1}};if($a=='find'){return($3)}else if($a=='rem'){rem('quests',$3)}}}//$a=find,add,rem | $b=name | $c=add data
function tag($a,$b,$c) {let $1=pid.indexOf($a);let $2=ptag[$1].split('!');let $3=$2.indexOf($b);if($c==u){if($3==-1){return(false)}else{return(ptagd[$1].arr($3))}}else{if($3==-1){ptag[$1]+='!'+$b;ptagd[$1]+='!'+$c}else{ptagd[$1]=ptagd[$1].arr($3,$c)}}}//$a=pid,$b=tag,$c=tag data
function heal($a=1,$b=0,$c) {let $1=($d)=>{window[$d][0]+=$a*window[$d][2]+Number($b);sbu($d)};if($c==u){['hp','ep','sp'].forEach($1)}else{$1($c)}}//heal(regen multi,add,type)
function genchunks() {let $1=Array(wsize[cworldid]*wsize[cworldid]);chunk=Array.from($1,()=>{return(`${terrains[rng(terrains.length-1)]}!${majorfeatures[rng(majorfeatures.length-1)]}!${minorfeatures[rng(minorfeatures.length-1)]}`)});chunkd=Array.from($1,()=>{return("!!")})}
function genpsn($a=Array(7)) {let $1=[pid[pid.length-1]+1,window['namegen'+namegennum](),''+rng(3)+rng(3)+rng(1),0,rng(2,1),rng(81,18),0,x,x];if($a[0]!=u){$1[1]=$a[0]};if($a[1]!=u){$1[2]=$a[1]};if($a[2]!=u){$1[3]=Number($a[2])};if($a[3]!=u){$1[4]=Number($a[3])};if($a[4]!=u){$1[5]=Number($a[4])};if($a[5]!=u){$1[7]=$a[5]};if($a[6]!=u){$1[8]=$a[6]};add('person',$1);return($1[0])}
function next($a=_,$b=2) {let $1=document.createElement("script");if($b>1){_=$a};document.body.appendChild($1);$1.id="script"+$b;$1.src="content/"+$a+".js"}
function xp($a,$b=0,$c=1) {let $1=aff.indexOf($a);affxp[$1]+=Math.floor($b/(Math.max(afflvl[$1]-(8-affr[$1]),1)))*$c;if(affxp[$1]>99){affxp[$1]-=100;if(affr!=9){afflvl[$1]+=1}}}//$a=affinity. $b=xp add amount. $c=xp quality.
function xp2($a,$b=0,$c=1) {let $1=pid.indexOf($a);pxp[$1]+=Math.floor($b/lvl[$1])*$c;if(pxp[$1]>99){pxp[$1]-=100;lvl[$1]+=1}}//xp for characters
function ptime($a) {let $2=[60,24,28,14];$a.forEach(($b,$c)=>{time[$c]+=$b});$2.forEach(($b,$c)=>{if(time[$c]>=$b){time[$c]-=$b;time[$c+1]+=1}});if(time[3]==0&&time[2]>0){time[3]+=1;time[2]-=1};fun('hour',time[1]+':'+num(time[0]))}//increases time by [minute,hour,day,month,year] ex: [5] would be be minutes and [0,1] would be an hour
function data($a,$b){if($b==u){return(chunkd[loc()].arr($a).split(','))}else{chunkd[loc()]=chunkd[loc()].arr($a,$b.join())}}//$a is the chunk data selector (0-2) | $b saves array data as chunk data
function tmpr($a=x,$b=0,$c=x,$d='0') {tmp=$a;tmpn=Number($b);tmpa=$c.split(',');tmpan=$d.split(',').map(Number)}//used to reset/redefine tmp variables
function iuse($a) {let $1=arr('item',$a);if($1[2]==0||$1[2]==1){equip($a,$1)}else if($1[2]==2){eval($1[4]);rem('item',$a)}else if($1[2]==3||$1[2]==4){return(u)}else if($1[2]==5){$1[4].split('!').forEach(($c,$d)=>{heal(0,$c,['hp','ep','sp'][$d])})}else if($1[2]==6){eval($1[4])}}
function equip($a,$b) {let $1=0;if($b[2]==0){if(eqp[0]!=0){$1=eqp[0];$b[4].split('!').slice(1,4).forEach(($c,$d)=>{atk[$d]-=Number($c)});tech[0]=0;eqp[0]=0};if($1!=$a){eqp[0]=$a;let $2=$b[4].arr(0);if(!aff.includes($2)){add('affinity',[$2,1,8,1,0])};tech[0]=aff.indexOf($2);$b[4].split('!').slice(1,4).forEach(($c,$d)=>{atk[$d]+=Number($c)})}}else if($b[2]==1){if(eqp[1]!=0){$1=eqp[1];$b[4].split('!').slice(0,3).forEach(($c,$d)=>{def[$d]-=Number($c)});eqp[1]=0};if($1!=$a){eqp[1]=$a;$b[4].split('!').slice(0,3).forEach(($c,$d)=>{def[$d]+=Number($c)})}}}//used in iuse function
function rem($a,$b,$c=1){let $1=$b;let $2=1;if(isNaN($b)){$1=window[window[$a][0]].indexOf($b)};if($a=='item'||$a=='material'){window[window[$a][1]][$1]-=$c;if(window[window[$a][1]][$1]>0){$2=0}};if($2==1){window[$a].forEach(($d)=>{window[$d].splice($1,1)})}}//removes an index fromm array groups or an item/material
function add($a,$b){if($a=='item'&&itm.includes($b[0])){itma[itm.indexOf($b[0])]+=Number($b[1])}else if($a=='material'&&mat.includes($b[0])){mata[mat.indexOf($b[0])]+=Number($b[1])}else{window[$a].forEach(($c,$d)=>{if(typeof(window[$c][0])=='string'){window[$c].push($b[$d])}else{window[$c].push(Number($b[$d]))}})}}
function sbu($a=['hp','ep','sp']) {if(Array.isArray($a)){$a.forEach(sbu)}else{let $1=[window[$a][0],window[$a][1]];if($1[0]>$1[1]){window[$a][0]=$1[1];$1=100}else if($1[0]<0){window[$a][0]=0;$1=0}else{$1=(100*$1[0]/$1[1]).toFixed()};elm($a+"bar").style.width=$1+"%";$1=Math.floor($1/20);elm($a+"bar").style.background=cc[$1];fun($a+"text",col(cc[$1],window[$a][0])+" ("+window[$a][1]+")")}}
//script functions
function loc($a=0,$b=0) {let $1=wsize[cworldid];let $2=[$a,$b];if($a=='d'){$2[1]=$b;$2[0]=rdirection[$2[1]];$2[1]=rdirection[8+Number($2[1])]};return((cycle($1,pos[0]+$2[0])*$1)+cycle($1,pos[1]+$2[1]))}//returns the chunk index for the relative pos (or direction if loc('d',direction/pos[2]))
function rng($a,$b=0) {return(Math.floor(Math.random()*($a+1))+$b)}
function num($a) {let $1=$a;if($1<10&&$1>-10){if($1<0){$1='-0'+Math.abs($1)}else{$1='0'+$1}};return($1)}//used in ptime, returns a string that adds a 0 before 1 digit numbers
function ctime($a) {let $1=time[0]/60/24+time[1]/24+time[2]+time[3]*28+time[4]*365;let $2=$a[0]/60/24+$a[1]/24+$a[2]+$a[3]*28+$a[4]*365;if($1>$2){return(true)}else{return(false)}}//compares current time with input time to determine whether it has passed input time
function cycle($a,$b) {if($a==1){return(0)}else if($b<0){return($a+($b%-$a))}else{return($b%$a)}}//Get overflow number ex: cycle(5,2)=2 and cycle(5,7)=2
function date() {return(Date().slice(4,-33))}//used for save info
function arr($a,$b){let $1=[];window[$a].forEach(($c)=>{$1.push(window[$c][$b])});return($1)}//$a=category $b=index | returns the values from an array group (ex: item or person)
function menu($a) {let $1=['character','items','savemenu','settings','cheats'];if($a==m){elm('infodis').style.display=x;m=0}else{next("menu/"+$1[$a-1],0);elm('infodis').style.display="block";m=$a}}
function namegen1(){let $1=rng(2,1);let $2=rng(2,1);let $3=nvow1.length;$4=ncon1.length;let $5='';let $6='';while($1>0){$5+=ncon1[rng($4-1)]+nvow1[rng($3-1)];$1-=1};$5=$5[0].toUpperCase()+$5.slice(1);while($2>0){$6+=ncon1[rng($4-1)]+nvow1[rng($3-1)];$2-=1};$6=$6[0].toUpperCase()+$6.slice(1);return($5+' '+$6)}
function namegen2(){let $1=rng(3,1);let $2=rng(3,1);let $3=ncon2.length;let $4='';let $5='';while($1>0){$4+=ncon2[rng($3-1)];$1-=1};while($2>0){$5+=ncon2[rng($3-1)];$2-=1};$4=$4[0].toUpperCase()+$4.slice(1);$5=$5[0].toUpperCase()+$5.slice(1);return($4+' '+$5)}
function namegen3(){let $1=rng(4,2);let $2=rng(4,2);let $3=ncon3.length;let $4='';let $5='';while($1>0){$4+=ncon3[rng($3-1)];$1-=1};while($2>0){$5+=ncon3[rng($3-1)];$2-=1};$4=$4[0].toUpperCase()+$4.slice(1);$5=$5[0].toUpperCase()+$5.slice(1);return($4+' '+$5)}
function end($a=2) {elm("script"+$a).remove();if($a==2){fun('txt',t);fun('nav',n)}}
function elm($a){return(document.getElementById($a))}
//save/load functions
function varld() {sv=sv.split('¦');sv[0]=sv[0].split('§');arrn.forEach(($a,$b)=>{window[arrn[$b]]=sv[0][$b].split('°').map(Number)});sv[1]=sv[1].split('§');arrs.forEach(($a,$b)=>{window[arrs[$b]]=sv[1][$b].split('°')});t=sv[2];n=sv[3];reset()}
function varsv() {sv=[[],[],[],[],'',''];reset('s');arrn.forEach(($a,$b)=>{sv[0].push(window[arrn[$b]].join('°'))});sv[0]=sv[0].join('§');arrs.forEach(($a,$b)=>{sv[1].push(window[arrs[$b]].join('°'))});sv[1]=sv[1].join('§');sv[2]=t;sv[3]=n;sv=sv.join("¦")}
function reset($a) {let $1;let $2;if($a=='s'){ss=[];sn=[];$1=($b)=>ss.push(window[$b]);$2=($b)=>sn.push(window[$b])}else{$1=($b,$c)=>window[$b]=ss[$c];$2=($b,$c)=>window[$b]=sn[$c];fun('txt',t);fun('nav',n);sbu();ptime([0])};strv.forEach($1);numv.forEach($2);next("menu/settings",0)}
function save($a) {varsv();if($a=='file'){elm("fdl").href="data:text/plain,"+encodeURIComponent(sv);elm("fdl").download="UG Save ("+date()+").txt";elm("fdl").click()}else{localStorage["UG "+$a]=sv;saves[$a]=date();localStorage.UGS=saves.join()}}
function load($a) {sv=localStorage["UG "+$a];varld()}
async function loadfile($a) {sv=await $a.text();varld()}
